// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/24/2024, 7:23:49 PM
const configMerger = require("/home/michal/tutorials/vet-app-front/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/home/michal/tutorials/vet-app-front/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/michal/tutorials/vet-app-front/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/michal/tutorials/vet-app-front/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/michal/tutorials/vet-app-front/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/michal/tutorials/vet-app-front/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/michal/tutorials/vet-app-front/plugins/**/*.{js,ts,mjs}","/home/michal/tutorials/vet-app-front/composables/**/*.{js,ts,mjs}","/home/michal/tutorials/vet-app-front/utils/**/*.{js,ts,mjs}","/home/michal/tutorials/vet-app-front/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/michal/tutorials/vet-app-front/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/michal/tutorials/vet-app-front/app.config.{js,ts,mjs}"] }));

module.exports = config
